### PR TITLE
chore(i18n): update l10n

### PR DESCRIPTION
**Pull request by Misaka13514**
Modifications:

- Full-width to half-width symbols in `ja.json` (sync with zh).
- Clear read-only strings `l10n_cmd_set.style_0` and `l10n_cmd_set.style_1`.
- Change `) 。` to `)。`.
- Add a period at the end of each line of the steps in [en.json#L43](https://github.com/Rongronggg9/RSS-to-Telegram-Bot/blob/dev/src/i18n/en.json#L43) and same in the corresponding location of all i18n files.
- Change `https://exmaple.com` to `https://example.com`.
- Remove irregular spaces in `fr.json`.

### CODE REVIEW

**Comment by Rongronggg9** [comment]
>     * Add a period at the end of each line of the steps in [en.json#L43](https://github.com/Rongronggg9/RSS-to-Telegram-Bot/blob/dev/src/i18n/en.json?rgh-link-date=2022-08-16T03%3A51%3A20Z#L43) and same in the corresponding location of all i18n files.
> 
>     * Change `https://exmaple.com` to `https://example.com`.

Sure. Just go ahead.

**Comment by Rongronggg9** [comment]
> sync with zh

You don't really need to sync with `zh` since I know that Japanese fall in love with full-width symbols :)
But it is OK to adopt half-width ones. My concern is the stupid text rendering of Telegram — it does not prefer wrapping at full-width symbols. That's why I adopted half-width symbols in `zh` l10ns.

**Comment by Misaka13514** [comment]
There are some irregular spaces in `fr.json`, I'm fixing them.

**Review by Misaka13514 — COMMENTED** [review]
LGTM now

**Review by Rongronggg9 — APPROVED** [review]

**Comment by Rongronggg9** [comment]
> Remove irregular spaces in `fr.json`.

Oh, they are regular. I will have a slight manual fix later.

https://forum.wordreference.com/threads/fr-space-before-a-colon-semicolon-question-mark-or-exclamation-point.54376/

**Pull request merged**
