### PR TITLE
chore(i18n): update l10n for `he`

### PR DESCRIPTION
**Pull request by RedSiskin**
Hebrew translate 1 to 88

### CODE REVIEW

**Comment by Rongronggg9** [comment]
Thanks for your translation.

I noticed that you haven't finished translating all strings - is the PR still WIP? Your confirmation is important: If it is ready to be merged, that's OK to have some strings untranslated and I will merge it.

I also noticed that you renamed `en.json` to `He.json`, which made CI fail. I will fix it before merging, so just ignore the failure of CI and move on if you think your translation is unfinished.

**Comment by RedSiskin** [comment]
> Thanks for your translation.
> 
> I noticed that you haven't finished translating all strings - is the PR still WIP? Your confirmation is important: If it is ready to be merged, that's OK to have some strings untranslated and I will merge it.
> 
> I also noticed that you renamed `en.json` to `He.json`, which made CI fail. I will fix it before merging, so just ignore the failure of CI and move on if you think your translation is unfinished.

I am sorry i am not sure how to use Github ...i completely finished the translation but then it said it got deleted, so i thought it got deleted by you.
Now i am not sure how to find the completed file ?!

**Comment by Rongronggg9** [comment]
> i completely finished the translation but then it said it got deleted, so i thought it got deleted by you.

Nope. I didn't touch anything in this PR. Had I touched it, you would have seen a record on this page.

> Now i am not sure how to find the completed file ?!

It was probably unsaved before you closed the editing page. I am willing to help but can't do anything in such a circumstance.

**Comment by RedSiskin** [comment]
> > i completely finished the translation but then it said it got deleted, so i thought it got deleted by you.
> 
> Nope. I didn't touch anything in this PR. Had I touched it, you would have seen a record on this page.
> 
> > Now i am not sure how to find the completed file ?!
> 
> It was probably unsaved before you closed the editing page. I am willing to help but can't do anything in such a circumstance.

**can you locate this files somehow ?**

Update and rename en.json to He.json

Hebrew translate 1 to 88

Update He.json

88-143 updated

**Comment by Rongronggg9** [comment]
> **can you locate this files somehow ?**
> 
> Update and rename en.json to He.json
> 
> Hebrew translate 1 to 88
> 
> Update He.json
> 
> 88-143 updated

Yes. You've made these two commits two weeks ago and I've seen them.

**Review by Rongronggg9 — APPROVED** [review]

**Pull request merged**
